from enum import Enum


class ErrorCode(str, Enum):
    """Códigos de error estables expuestos por la API."""

    APP_ERROR = "APP_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TOKEN_REQUIRED = "TOKEN_REQUIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    CSRF_INVALID = "CSRF_INVALID"
    REFRESH_FAILED = "REFRESH_FAILED"

    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    CONFLICT = "CONFLICT"
