"""add unique email to users

Revision ID: 1975fc61a54b
Revises: 898eeb162f00
Create Date: 2026-10-09 16:49:39.995371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1975fc61a54b'
down_revision: Union[str, Sequence[str], None] = '898eeb162f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_usuario_email', 'usuario', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usuario_email', 'usuario', type_='unique')
    # ### end Alembic commands ###
