"""initial schema

Revision ID: 898eeb162f00
Revises: 
Create Date: 2026-10-09 10:32:07.237297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '898eeb162f00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('icon_number', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_categoria_slug'),
    schema='public'
    )
    op.create_index('ix_categoria_nombre', 'categoria', ['nombre'], unique=False, schema='public')
    op.create_index(op.f('ix_public_categoria_is_deleted'), 'categoria', ['is_deleted'], unique=False, schema='public')
    op.create_table('config_puntos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('factor_asignacion_puntos', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('factor_costo_vale', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name='ck_config_puntos_rango_fechas'),
    sa.CheckConstraint('factor_asignacion_puntos > 0', name='ck_config_puntos_factor_asignacion_positivo'),
    sa.CheckConstraint('factor_costo_vale > 0', name='ck_config_puntos_factor_costo_positivo'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_config_puntos_is_deleted'), 'config_puntos', ['is_deleted'], unique=False, schema='public')
    op.create_table('errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack', sa.Text(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_errors_created_at', 'errors', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_errors_is_deleted'), 'errors', ['is_deleted'], unique=False, schema='public')
    op.create_table('negocio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('tipo', sa.Enum('MAIN', 'SOCIO', name='tipo_negocio', schema='public'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tipo', name='uq_negocio_id_tipo'),
    schema='public'
    )
    op.create_index('ix_negocio_nombre', 'negocio', ['nombre'], unique=False, schema='public')
    op.create_index('ix_negocio_tipo', 'negocio', ['tipo'], unique=False, schema='public')
    op.create_index(op.f('ix_public_negocio_is_deleted'), 'negocio', ['is_deleted'], unique=False, schema='public')
    op.create_table('sucursal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('url_ubicacion', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('negocio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['public.negocio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'negocio_id', name='uq_sucursal_id_negocio_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sucursal_is_deleted'), 'sucursal', ['is_deleted'], unique=False, schema='public')
    op.create_index('ix_sucursal_negocio_id', 'sucursal', ['negocio_id'], unique=False, schema='public')
    op.create_table('vale',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('total_puntos', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('total_costo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('negocio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['public.categoria.id'], ),
    sa.ForeignKeyConstraint(['negocio_id'], ['public.negocio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'negocio_id', name='uq_vale_id_negocio_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_vale_is_deleted'), 'vale', ['is_deleted'], unique=False, schema='public')
    op.create_index('ix_vale_categoria_id', 'vale', ['categoria_id'], unique=False, schema='public')
    op.create_index('ix_vale_negocio_id', 'vale', ['negocio_id'], unique=False, schema='public')
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('ci', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN', 'CAJERO', 'CLIENTE', 'SOCIO', name='role_usuario', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('genero', sa.Enum('M', 'F', 'O', name='genero_usuario', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('apellidos', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('sucursal_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('puntos >= 0', name='ck_usuario_puntos_no_negativos'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['public.sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci', name='uq_usuario_ci'),
    schema='public'
    )
    op.create_index(op.f('ix_public_usuario_is_deleted'), 'usuario', ['is_deleted'], unique=False, schema='public')
    op.create_index('ix_usuario_role', 'usuario', ['role'], unique=False, schema='public')
    op.create_index('ix_usuario_sucursal_id', 'usuario', ['sucursal_id'], unique=False, schema='public')
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=64), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.CheckConstraint('(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)', name='ck_auth_sessions_revocation_consistency'),
    sa.CheckConstraint('expires_at > created_at', name='ck_auth_sessions_expiration_after_creation'),
    sa.CheckConstraint('replaced_by IS NULL OR replaced_by <> id', name='ck_auth_sessions_replacement_not_self'),
    sa.CheckConstraint('replaced_by IS NULL OR revoked_at IS NOT NULL', name='ck_auth_sessions_replacement_requires_revocation'),
    sa.ForeignKeyConstraint(['replaced_by'], ['public.auth_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['public.usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('replaced_by', name='uq_auth_sessions_replaced_by'),
    schema='public'
    )
    op.create_index('ix_auth_sessions_expires_at', 'auth_sessions', ['expires_at'], unique=False, schema='public')
    op.create_index('ix_auth_sessions_family_id_revoked_at', 'auth_sessions', ['family_id', 'revoked_at'], unique=False, schema='public')
    op.create_index('ix_auth_sessions_user_id_revoked_at', 'auth_sessions', ['user_id', 'revoked_at'], unique=False, schema='public')
    op.create_index(op.f('ix_public_auth_sessions_is_deleted'), 'auth_sessions', ['is_deleted'], unique=False, schema='public')
    op.create_index('ux_auth_sessions_refresh_token_hash', 'auth_sessions', ['refresh_token_hash'], unique=True, schema='public')
    op.create_table('canje',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('dador_id', sa.Uuid(), nullable=True),
    sa.Column('vale_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'CANJEADO', 'EXPIRADO', 'CANCELADO', name='estado_canje', schema='public'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('codigo_canje', sa.String(length=6), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('negocio_id', sa.Uuid(), nullable=False),
    sa.Column('total_puntos', sa.Integer(), nullable=False),
    sa.Column('total_costo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('config_punto_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("codigo_canje ~ '^[0-9]{6}$'", name='ck_canje_codigo_seis_digitos'),
    sa.ForeignKeyConstraint(['cliente_id'], ['public.usuario.id'], ),
    sa.ForeignKeyConstraint(['config_punto_id'], ['public.config_puntos.id'], ),
    sa.ForeignKeyConstraint(['dador_id'], ['public.usuario.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id', 'negocio_id'], ['public.sucursal.id', 'public.sucursal.negocio_id'], name='fk_canje_sucursal_negocio'),
    sa.ForeignKeyConstraint(['vale_id', 'negocio_id'], ['public.vale.id', 'public.vale.negocio_id'], name='fk_canje_vale_negocio'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_canje', name='uq_canje_codigo_canje'),
    schema='public'
    )
    op.create_index('ix_canje_cliente_id', 'canje', ['cliente_id'], unique=False, schema='public')
    op.create_index('ix_canje_config_punto_id', 'canje', ['config_punto_id'], unique=False, schema='public')
    op.create_index('ix_canje_dador_id', 'canje', ['dador_id'], unique=False, schema='public')
    op.create_index('ix_canje_negocio_id', 'canje', ['negocio_id'], unique=False, schema='public')
    op.create_index('ix_canje_status', 'canje', ['status'], unique=False, schema='public')
    op.create_index('ix_canje_sucursal_id', 'canje', ['sucursal_id'], unique=False, schema='public')
    op.create_index('ix_canje_vale_id', 'canje', ['vale_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_canje_is_deleted'), 'canje', ['is_deleted'], unique=False, schema='public')
    op.create_table('operacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('receptor_id', sa.Uuid(), nullable=False),
    sa.Column('emisor_id', sa.Uuid(), nullable=False),
    sa.Column('total_compra', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_puntos', sa.Integer(), nullable=False),
    sa.Column('config_punto_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Uuid(), nullable=False),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.CheckConstraint('emisor_id <> receptor_id', name='ck_operacion_emisor_receptor_diferentes'),
    sa.ForeignKeyConstraint(['config_punto_id'], ['public.config_puntos.id'], ),
    sa.ForeignKeyConstraint(['emisor_id'], ['public.usuario.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['public.usuario.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['public.sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_operacion_config_punto_id', 'operacion', ['config_punto_id'], unique=False, schema='public')
    op.create_index('ix_operacion_emisor_id', 'operacion', ['emisor_id'], unique=False, schema='public')
    op.create_index('ix_operacion_receptor_id', 'operacion', ['receptor_id'], unique=False, schema='public')
    op.create_index('ix_operacion_sucursal_id', 'operacion', ['sucursal_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_operacion_is_deleted'), 'operacion', ['is_deleted'], unique=False, schema='public')
    op.create_table('movimientos_puntos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ACUMULA', 'CANJE', 'AJUSTE', 'EXPIRA', name='tipo_movimiento', schema='public'), nullable=False),
    sa.Column('puntos', sa.BigInteger(), nullable=False),
    sa.Column('operacion_id', sa.Uuid(), nullable=True),
    sa.Column('canje_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("(tipo_movimiento = 'ACUMULA' AND operacion_id IS NOT NULL AND canje_id IS NULL) OR (tipo_movimiento = 'CANJE' AND canje_id IS NOT NULL AND operacion_id IS NULL) OR (tipo_movimiento IN ('AJUSTE', 'EXPIRA') AND operacion_id IS NULL AND canje_id IS NULL)", name='ck_movimientos_puntos_referencia_por_tipo'),
    sa.ForeignKeyConstraint(['canje_id'], ['public.canje.id'], ),
    sa.ForeignKeyConstraint(['operacion_id'], ['public.operacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['public.usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('ix_movimientos_puntos_canje_id', 'movimientos_puntos', ['canje_id'], unique=False, schema='public')
    op.create_index('ix_movimientos_puntos_operacion_id', 'movimientos_puntos', ['operacion_id'], unique=False, schema='public')
    op.create_index('ix_movimientos_puntos_usuario_id', 'movimientos_puntos', ['usuario_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_movimientos_puntos_is_deleted'), 'movimientos_puntos', ['is_deleted'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_movimientos_puntos_is_deleted'), table_name='movimientos_puntos', schema='public')
    op.drop_index('ix_movimientos_puntos_usuario_id', table_name='movimientos_puntos', schema='public')
    op.drop_index('ix_movimientos_puntos_operacion_id', table_name='movimientos_puntos', schema='public')
    op.drop_index('ix_movimientos_puntos_canje_id', table_name='movimientos_puntos', schema='public')
    op.drop_table('movimientos_puntos', schema='public')
    op.drop_index(op.f('ix_public_operacion_is_deleted'), table_name='operacion', schema='public')
    op.drop_index('ix_operacion_sucursal_id', table_name='operacion', schema='public')
    op.drop_index('ix_operacion_receptor_id', table_name='operacion', schema='public')
    op.drop_index('ix_operacion_emisor_id', table_name='operacion', schema='public')
    op.drop_index('ix_operacion_config_punto_id', table_name='operacion', schema='public')
    op.drop_table('operacion', schema='public')
    op.drop_index(op.f('ix_public_canje_is_deleted'), table_name='canje', schema='public')
    op.drop_index('ix_canje_vale_id', table_name='canje', schema='public')
    op.drop_index('ix_canje_sucursal_id', table_name='canje', schema='public')
    op.drop_index('ix_canje_status', table_name='canje', schema='public')
    op.drop_index('ix_canje_negocio_id', table_name='canje', schema='public')
    op.drop_index('ix_canje_dador_id', table_name='canje', schema='public')
    op.drop_index('ix_canje_config_punto_id', table_name='canje', schema='public')
    op.drop_index('ix_canje_cliente_id', table_name='canje', schema='public')
    op.drop_table('canje', schema='public')
    op.drop_index('ux_auth_sessions_refresh_token_hash', table_name='auth_sessions', schema='public')
    op.drop_index(op.f('ix_public_auth_sessions_is_deleted'), table_name='auth_sessions', schema='public')
    op.drop_index('ix_auth_sessions_user_id_revoked_at', table_name='auth_sessions', schema='public')
    op.drop_index('ix_auth_sessions_family_id_revoked_at', table_name='auth_sessions', schema='public')
    op.drop_index('ix_auth_sessions_expires_at', table_name='auth_sessions', schema='public')
    op.drop_table('auth_sessions', schema='public')
    op.drop_index('ix_usuario_sucursal_id', table_name='usuario', schema='public')
    op.drop_index('ix_usuario_role', table_name='usuario', schema='public')
    op.drop_index(op.f('ix_public_usuario_is_deleted'), table_name='usuario', schema='public')
    op.drop_table('usuario', schema='public')
    op.drop_index('ix_vale_negocio_id', table_name='vale', schema='public')
    op.drop_index('ix_vale_categoria_id', table_name='vale', schema='public')
    op.drop_index(op.f('ix_public_vale_is_deleted'), table_name='vale', schema='public')
    op.drop_table('vale', schema='public')
    op.drop_index('ix_sucursal_negocio_id', table_name='sucursal', schema='public')
    op.drop_index(op.f('ix_public_sucursal_is_deleted'), table_name='sucursal', schema='public')
    op.drop_table('sucursal', schema='public')
    op.drop_index(op.f('ix_public_negocio_is_deleted'), table_name='negocio', schema='public')
    op.drop_index('ix_negocio_tipo', table_name='negocio', schema='public')
    op.drop_index('ix_negocio_nombre', table_name='negocio', schema='public')
    op.drop_table('negocio', schema='public')
    op.drop_index(op.f('ix_public_errors_is_deleted'), table_name='errors', schema='public')
    op.drop_index('ix_errors_created_at', table_name='errors', schema='public')
    op.drop_table('errors', schema='public')
    op.drop_index(op.f('ix_public_config_puntos_is_deleted'), table_name='config_puntos', schema='public')
    op.drop_table('config_puntos', schema='public')
    op.drop_index(op.f('ix_public_categoria_is_deleted'), table_name='categoria', schema='public')
    op.drop_index('ix_categoria_nombre', table_name='categoria', schema='public')
    op.drop_table('categoria', schema='public')
    # ### end Alembic commands ###
