"""update categoria field lengths

Revision ID: d250a36afff2
Revises: 1975fc61a54b
Create Date: 2026-10-10 08:38:29.891509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd250a36afff2'
down_revision: Union[str, Sequence[str], None] = '1975fc61a54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categoria', 'nombre',
               existing_type=sa.VARCHAR(length=120),
               type_=sqlmodel.sql.sqltypes.AutoString(length=60),
               existing_nullable=False)
    op.alter_column('categoria', 'slug',
               existing_type=sa.VARCHAR(length=160),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categoria', 'slug',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('categoria', 'nombre',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=60),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
